Complete App
emmyobonyo/travel-notes pull request #1
Opened 2022-02-15 19:30 UTC by emmyobonyo

### Tasks Completed
- Built the entire App.

2022-02-16 11:01 UTC, raybesiga commented
Hi @emmyobonyo 

I have a few questions. What is the goal of the app? I would expect that I am able to:

- View each location on the map
- Maybe have a detail view for the specific trip
- Have a photo gallery or detail post for each trip post

Putting ideas forward. Thoughts?

2022-02-17 06:47 UTC, KnightWorker37 requested changes
This is not OK. There should be multiple features as different branches showing the evolution of the code. The changes/PR is just too big!

For example things like git bisect will not work to find regressions...

2022-02-17 06:53 UTC, KnightWorker37 requested changes

2022-02-17 06:53 UTC, KnightWorker37 commented on src/header/Header.js
> +        <img src={`./images/logo.png`} className="header-image" alt="logo" />
I wonder if this works?
```suggestion
        <img src="./images/logo.png" className="header-image" alt="logo" />
```
Or:
```
import logo from './images/logo.png';
```
then
```suggestion
        <img src={logo} className="header-image" alt="logo" />
```

2022-02-17 09:45 UTC, emmyobonyo commented on src/header/Header.js
> +        <img src={`./images/logo.png`} className="header-image" alt="logo" />
Hello @raybesiga 

Thanks for the suggestions. They're all really good suggestions.
1. **View each location on a map.** This is a wonderful idea and I'll definitely implement it. 

The other two suggestions are equally great. But they were not part of the description as per the design. Kindly look at the Figma design ( https://www.figma.com/file/YhtX4VSXpgUB4y1HnAeqBq/Travel-Journal-(Copy)?node-id=0%3A1 ). I know it's wonderful to sometimes go above and beyond but time is also a limited resource. I was suggesting I focus on what the tutorial requires at the moment, just to be able to move quickly, and start contributing earlier. 

The goal on this particular project was to **learn** how to pick data from an API.

2022-02-17 09:47 UTC, emmyobonyo commented on src/header/Header.js
> +        <img src={`./images/logo.png`} className="header-image" alt="logo" />
Hello @KnightWorker37 

Your suggestion is really good. My images are currently stored in the `public` folder and I can't access them from the `src` folder, so that was the only alternative. The instructor says though that He will teach how to keep all images in the `src` folder in a later tutorial.

2022-05-28 09:07 UTC, merged